version: '3'

volumes:
    app:
    database:
    redis:

services:
    flask-app:

        image: souaddjerfi/flask-app:latest
        container_name: flask-app
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - app:/app
        depends_on:
           - mysql-db
           - redis-db    
        
    mysql-db:
        container_name: mysql-db
        #build: ./database/
        image: souaddjerfi/mysql-db:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
        ports:
            - '3306:3306'
        volumes:
            - database:/var/lib/mysql
        
    redis-db:
        container_name: redis-db
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis:/data    
        

              






