version: '3'

volumes:
    app:
    database:

services:
    flask-app:
        container_name: flask-app
        build: ./python/
        #command: sh -c "sleep 10s; python3 ./app.py"
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - app:/app
        depends_on:
           - mysql-db
           - redis-db    
        networks:
            - backend

    mysql-db:
        container_name: mysql-db
        build: ./database/
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: app
            MYSQL_PASSWORD: 
            MYSQL_DATABASE: test
        ports:
            - '3306:3306'
        volumes:
            - database:/var/lib/mysql
        networks:
            - backend

    redis-db:
        container_name: redis-db
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        networks:
            - backend       

networks:
    backend:




