# étapes à ajouter dans le vagrantfile
- name: check connection
      ping:

    - name: Update apt packages     
      apt: 
        update_cache: yes

    - name: update docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: installer docker module pour python
      pip:
        name: docker

    - name: install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: install docker-compose
      apt:
        name: docker-compose
        state: latest
        update_cache: true

    - name: copier docker-compose.yml
      copy:
        src: projet-devops/docker-compose.yml
        dest: /tmp/