pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
        stage('Build docker image') {
            agent {
                docker {
                    image 'python:3.9.10-alpine3.14'
                }
            }
            steps {
                sh 'docker build -t image-rouge-jenkins'
            }
        }        
    }
}